FROM payara/micro:6.2024.6-jdk17

COPY dist/SoemOficial_Teriminadisimo.war /opt/payara/deployments/soem-oficial.war

EXPOSE 8080

CMD ["--deploy", "/opt/payara/deployments/soem-oficial.war", "--port", "8080"]
